modLoader = "javafml"
loaderVersion = "[1,)"
license = "LGPLv3"
issueTrackerURL = "https://github.com/Fallen-Breath/classic-gamerule/issues"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
displayURL = "https://github.com/Fallen-Breath/classic-gamerule"
authors = "Fallen_Breath"
description = '''
Bring back the classic camel-case gamerules to MC 1.21.11+
'''
logoFile = "icon.png"

[[dependencies."${id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_dependency}"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "${id}.mixins.json"
